### ISSUE TITLE
FAB + button throws UI error when pressed.

### ISSUE THREAD

**Issue by ChaoticTempest** [ucsdCSE110wi16/CSE110W240T3#11]
"Only the original thread that created a view hierarchy can touch its views."

**Comment by ChaoticTempest** [comment]
EntryPopup resolved it.

**Comment by ChaoticTempest** [comment]
The error is now thrown only when in a certain list and the + button is pressed.

**Comment by ChaoticTempest** [comment]
Issue fixed, will merge later. Async calls to Parse should NOT be changing the UI elements, such as: notifyDataSetHasChanged() => which causes the UI to be updated

**Comment by davidzech** [comment]
Fixed with https://github.com/ucsdCSE110wi16/CSE110W240T3/commit/6ed7678d4cec3e0273d6dec2a0953e558f554c36
