### ISSUE TITLE
Spinner Items have White Text on White Background

### ISSUE THREAD

**Issue by davidzech** [ucsdCSE110wi16/CSE110W240T3#14]
The text for the categories in the new entry dialog spinner view is black on Emulator, but is white on real devices. This happened with both @ChaoticTempest HTC One M7, and my own HTC One M7.

**Comment by jimmyxgong** [comment]
Fixed in 0101beca931669980e5ef8430754a67d2d93eaf1 within entry-refactor

**Comment by ChaoticTempest** [comment]
Issue resolved. No longer using spinner: the material dialog is used instead since it makes for a better overall experience when choosing categories.
