### ISSUE TITLE
Material DatePicker doesnt need from/to dates

### ISSUE THREAD

**Issue by davidzech** [ucsdCSE110wi16/CSE110W240T3#21]
I don't see any option to disable this with the datepicker dialog we are using. Perhaps we'll use some 3rd party material date picker.

**Comment by ChaoticTempest** [comment]
Yeah. I'll have to go into the source and disable it myself. It's going to be a long process

**Comment by ChaoticTempest** [comment]
Fixed in e6373e6af4c347efd17c11d416408468021cf748
