### ISSUE TITLE
Images aren't saving?

### ISSUE THREAD

**Issue by davidzech** [ucsdCSE110wi16/CSE110W240T3#22]
mCurrentPhotoPath is always null

**Comment by jimmyxgong** [comment]
Should be fixed with f533c8ca46b11dbc58687fb61f54440655526a4f

**Comment by davidzech** [comment]
Fixed with 4c4e2a774077c0f3531dffc7cc159c51117e3479

**Comment by davidzech** [comment]
I didn't see any reason to have mCurrentPath and photoPath, so I just use them together

**Comment by jimmyxgong** [comment]
alright cool, ill delete the branch
